package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/goApp/db"
	"github.com/goApp/models"
)

func main() {
	server := gin.Default() //Create Gin server instance
	db.InitDB()             //Initialize Database

	//API endpoints
	server.GET("/ping", pingHandler)    //to check ping
	server.GET("/events", getAllEvents) //get all events
	server.POST("/events", createEvent) //create new event

	//start server
	server.Run(":8080") //localhost:8080
	fmt.Println("Server is running on http://localhost:8080")
}

func pingHandler(c *gin.Context) {
	c.JSON(200, gin.H{
		"message": "pong",
	})
}

func getAllEvents(c *gin.Context) {
	events := models.GetAllEvents()
	c.JSON(200, events)
}

func createEvent(c *gin.Context) {
	event := models.Event{}
	if err := c.ShouldBindJSON(&event); err != nil {
		fmt.Println("Error binding JSON:", err)
		c.JSON(400, gin.H{"error": "Request could not be parsed"})
		return
	}

	event.ID = 1     //In real application, ID will be generated by the database
	event.UserID = 1 //In real application, UserID will be fetched from the authenticated user context
	models.SaveEvent(event)
	c.JSON(201, gin.H{"message": "Event created", "event": event})
}
